### ISSUE TITLE
Create Basic Cytoscape App Demo

### ISSUE THREAD

**Issue by cannin** [cannin/causalpath_cytoscape_app#1]
This is the first task. Get a Cytoscape app demo working on your computer and install any necessary tools.

**Comment by cannin** [comment]
Thanks. Can you fill in the README with instructions on compiling and installing? Also, go ahead and rename the demo to "causalpath_cytoscape_app" and in other places as necessary as "CausalPath Cytoscape App"

**Comment by cannin** [comment]
@thepritam Also, remember to move issues to "In Progress" for the project as you are working on them.

**Comment by thepritam** [comment]
@cannin I have renamed the file as you have described.
Also Can you please elaborate more what should I write in compiling and installing part?
As far what I have done, I am opening the project in Intellij idea and there is install option which creates the jar file.
Then I put the jar file in this "<path to this>\CytoscapeConfiguration\3\apps\installed" in this directory. And open the cytoscape desktop app and run it from there.
Should I write this things in Readme as instruction.
Please let me know.

**Comment by thepritam** [comment]
I have updated the Readme the with instructions to install and run the app. Please let me know if I need to add any other information regarding the same.
