### ISSUE TITLE
Use Force-Directed Layout for App

### ISSUE THREAD

**Issue by cannin** [cannin/causalpath_cytoscape_app#14]
This is related to #13 

Use this layout: 
http://manual.cytoscape.org/en/stable/Navigation_and_Layout.html#prefuse-force-directed-layout

instead of the grid layout here: 

https://github.com/cannin/causalpath_cytoscape_app/blob/41c8be4f5467e52ef2287562563fec10c3036e0a/casualpath-cytoscape-app/src/main/java/org/cytoscape/sample/internal/utils/CyNetworkUtils.java#L81

**Comment by thepritam** [comment]
@cannin  I have able to do this successfully.  
The command I have used is given as follows:
```
 CommandExecutor.execute("layout force-directed network=\"" + networkName + "\"", cyServiceRegistrar);
```

**Comment by thepritam** [comment]
@cannin I am able to do this successfully. 
the command I have used is given as follows:
```
 CommandExecutor.execute("layout force-directed network=\"" + networkName + "\"", cyServiceRegistrar);
```

**Comment by thepritam** [comment]
I have did some trial error and it worked. 
And the following is the sample output. 
@cannin  please check it. 
![force-directed](https://user-images.githubusercontent.com/34870686/124655449-7bac3280-debd-11eb-8132-f0ec874d0f9c.PNG)
