### ISSUE TITLE
Apply Custom Style to Cytoscape Network

### ISSUE THREAD

**Issue by cannin** [cannin/causalpath_cytoscape_app#15]
These links may help apply a custom style to the network. 

* https://github.com/RBVI/stringApp/blob/master/src/main/java/edu/ucsf/rbvi/stringApp/internal/utils/ViewUtils.java#109
* https://groups.google.com/g/cytoscape-helpdesk/c/cUaOlyaxdaI

**Comment by cannin** [comment]
@thepritam 

This post: 
https://stackoverflow.com/questions/14298096/how-to-automate-load-export-operation-in-cytoscape 

has the command to load vizmap from path:
vizmap load file file="[full path to .xml style file]"

**Comment by thepritam** [comment]
@cannin @ozgunbabur I can apply the style programmatically from the format/JSON file. I have only added the border styles and node styles for the network.  The following is a sample network after applying the styles. 
![programstyle](https://user-images.githubusercontent.com/34870686/125211735-1645b080-e2c6-11eb-81d5-2a97ce753972.PNG)

**Comment by thepritam** [comment]
The following repositories are helpful for creating the style. 
## StEMAPApp
https://github.com/RBVI/StEMAPApp
## stringApp
https://github.com/RBVI/stringApp

**Comment by cannin** [comment]
@thepritam thanks, but are you sure the CausalPath style was applied? One obvious problem I see is that the arrowheads are black (black arrowheads are nowhere in the CausalPath style see #13)

**Comment by thepritam** [comment]
@cannin  I have applied the CausalPath styles for now I have considered the all-nodes color, all-nodes border color, and also the edge color. Now, I am aware that the edge tip color should be of green color but there is not function in the library that could change the edge tip color.  Although I can change the edge color by using the RGB color code you provided.

**Comment by thepritam** [comment]
I have asked about the edge tip color formatting in the Cytoscape app development. 
The following link describes my query:
https://groups.google.com/u/1/g/cytoscape-app-dev/c/lycOc00M-dg

**Comment by thepritam** [comment]
@cannin I am able to change the edge tip color on my own. 
Below is the sample code.  This property is not normally defined. So, we have to get the property class from the RenderingEngineManager. Many properties are not defined. And it is the way to do so. 
```
 VisualLexicon lex = cyServiceRegistrar.getService(RenderingEngineManager.class).getDefaultVisualLexicon();
        VisualProperty targetedgecolor = lex.lookup(CyEdge.class,"EDGE_TARGET_ARROW_UNSELECTED_PAINT");

        vs.setDefaultValue(targetedgecolor,Greencolor);
```
