### ISSUE TITLE
Complex Nodes Visualization in Cytoscape

### ISSUE THREAD

**Issue by cannin** [cannin/causalpath_cytoscape_app#17]
Are you able to use the advanced styles from Cytoscape in an app? 

http://manual.cytoscape.org/en/stable/Styles.html#tutorial-6-creating-node-charts

Could you convert the small circles on nodes into a graph? Can you try to create a demo accessing these features?

Also related: 
https://cytoscape.org/cytoscape-tutorials/protocols/custom-enhanced-graphics-style/#/12

**Comment by thepritam** [comment]
@cannin thank you for creating this issue. I have not started with individual node styles, I will get started with it. And thank you for the links.

**Comment by cannin** [comment]
A related suggestion by @AlexanderPico https://apps.cytoscape.org/apps/omicsvisualizer (the donut chart around a node); this option also requires the enhancedGraphics app.

**Comment by thepritam** [comment]
@cannin  I am able to do apply the enhanced graphics in the application. I have applied the pie chart for the annotations. I will be attaching a sample screenshot for the network in the issue #18. It is just a sample just to make sure it is working.

**Comment by thepritam** [comment]
@cannin I am able to add two annotations for a node for testing purposes and I can add more also.  And I have applied them as @ozgunbabur has explained last day where we start putting them from the top-left and go anticlockwise. And also, We don't need to give any empty style for the node. If it does not there we can simply ignore it.  
I am attaching a sample screenshot for the same. 

![multiplesites](https://user-images.githubusercontent.com/34870686/126914487-4d7fdf08-8885-487f-b7ea-602d4656db48.PNG)
