### ISSUE TITLE
Use enhancedGraphics app to Represent Annotation Data on a Node programmatically

### ISSUE THREAD

**Issue by cannin** [cannin/causalpath_cytoscape_app#18]
Represent the data for the annotations (little circles with Ps) using enhancedGraphics programmatically. I would start by using the charts feature as in this app: https://apps.cytoscape.org/apps/omicsvisualizer

**Comment by thepritam** [comment]
I have applied to applied the enhanced graphics to each node programmatically. For now, I have used only the same style for all the nodes just to make sure it is working. Below is a sample screenshot for the visualization.  I can change the size of it(not checked it but there is property to do so) and also change the color. 
I  need to figure out two things:

- Change the shape of it to circular
- put the p (or any other annotation ) inside it. 

![samplenhanchment](https://user-images.githubusercontent.com/34870686/126080819-6a8ae7e5-a592-45db-828e-9443228e8282.PNG)

**Comment by cannin** [comment]
Thanks. For the next test, can you create two P in two different style circles? Blue and Red with red and green circle border colors, respectively? After this test then we can try with real data.

**Comment by thepritam** [comment]
@cannin I will try to do it. We can apply upto 9 custom graphics for each node.

**Comment by thepritam** [comment]
@cannin I am uploading the updated visualization where I have changed the size, position, and color of the Circos chart.
The following image is a sample visualization.
![appliedenhancedgraphics](https://user-images.githubusercontent.com/34870686/126560727-70f5b341-7bdc-494f-abb0-c7ae9f5f512b.PNG)

**Comment by cannin** [comment]
@thepritam can you put the p in the circle and make the circle white instead of transparent?

**Comment by thepritam** [comment]
@cannin I can move the circles with the nodes.

**Comment by thepritam** [comment]
The link to documentation for the Circos charts :
https://apps.cytoscape.org/apps/enhancedgraphics
https://github.com/RBVI/enhancedGraphics/blob/master/README.md#circos

**Comment by cannin** [comment]
Thanks. Can you try: https://github.com/RBVI/enhancedGraphics/blob/master/README.md#label for the circle p?

**Comment by thepritam** [comment]
Okay sir. I will try to implement it.

**Comment by thepritam** [comment]
@cannin I am attaching the screenshot for the visualization of the Label Chart in each node. I have not applied any style except text and background color. And also positioned them which we need to change accordingly.  The size of node is also small which we also can change. 
![labelchartshot](https://user-images.githubusercontent.com/34870686/126711936-cac3f65b-0ffd-4d24-8ced-d237de3a87d4.PNG)

**Comment by thepritam** [comment]
@cannin I have update the padding and changed the position of the chart.
![labelchartshotnew](https://user-images.githubusercontent.com/34870686/126713060-b071f45d-1aa5-465e-981d-aa4ff02cb52c.PNG)
