### ISSUE TITLE
Create Result Panel to show information about the node

### ISSUE THREAD

**Issue by thepritam** [cannin/causalpath_cytoscape_app#23]
@cannin I am able to create the result panel and customized it based on the node's selection or deselection.  I am attaching a screenshot for the same. 
![selectconfiguration](https://user-images.githubusercontent.com/34870686/126913951-85dde0e1-2665-432f-a007-7fa460615c60.PNG)

**Comment by cannin** [comment]
@thepritam for the title of the panel just put "CausalPath"

**Comment by thepritam** [comment]
@cannin I will do that.
