### ISSUE TITLE
Edits to Interface

### ISSUE THREAD

**Issue by cannin** [cannin/causalpath_cytoscape_app#31]
- [x] The title in red, just say "CausalPath". 
- [x] Do not use italic text. 
- [x] With the exception of the title, make all font sizes the same
- [x] Remove the "Select files for visualization box", it is unnecessary since it will always be SIF and .format 

![121789677-62cd9b80-cbf5-11eb-9369-ae5d367cf075](https://user-images.githubusercontent.com/790284/128876960-8814f56a-dcf8-4930-8ab4-68914ef87d07.png)

**Comment by thepritam** [comment]
@cannin All the necessary changes have been to the UI.
