### ISSUE TITLE
Cytoscape Documentation

### ISSUE THREAD

**Issue by cannin** [cannin/causalpath_cytoscape_app#6]
We need documentation for BundleContext; it might be good to content Scooter Morris:

https://github.com/cannin/causalpath_cytoscape_app/blob/dc1c95b12ceed70391a5a8e0e2f97c7a7b342e24/CausalPath%20Cytoscape%20App/src/main/java/org/cytoscape/sample/internal/CyActivator.java#L19

**Comment by thepritam** [comment]
As I said in the meeting, there is a dedicated google group to ask Cytoscape app development-related queries.
Below is the link to join the community.
https://groups.google.com/u/1/g/cytoscape-app-dev

**Comment by thepritam** [comment]
As discussed in Today's meeting, I am listing some of the doubts for the app development.
There are some general topics for which I need help or require documentation and I am describing them one by one.
1. There is a file named CyActivator.java in every Cytoscape app. It also contains some classed e.g. CyActivator,AbstractCyActivator ,BundleContext ,CyApplicationManager. I need to understand what are the functionalities of each class. As far, I had understood it registers all services into a bundle. But I need to understand more clearly about the core concepts of all these classes. Also I need to understand the function registerService more clearly.
2.  There is an override function named run which takes a TaskMonitor object. I need to understand this method properly and what other functionality it does have.
3. what is the need for TaskIterator and what is the main purpose of it.
4.  In this given 
https://github.com/cannin/causalpath_cytoscape_app/tree/main/CausalPath%20Cytoscape%20App/src/main/java/org/cytoscape/sample/internal
there are two files ImportVisualStyleTask.java and ImportVisualStyleTaskFactory.java.
Why do we need to create a separate TaskFactory file for a particular task and also do we need to create a TaskFactory file for every separated task I incorporate in my app.
Please guide me to clarify these doubts. 
Thanks,

**Comment by cannin** [comment]
@thepritam check your email. Does it help?

**Comment by thepritam** [comment]
@cannin Thank you for your email. I found the Javadoc file when I was writing my proposal.  I was not able to understand it very clearly. I will try to find more clarity from this documentation as the work progresses.
