### ISSUE TITLE
Interface Design and Create 

### ISSUE THREAD

**Issue by thepritam** [cannin/causalpath_cytoscape_app#9]

**Comment by thepritam** [comment]
@cannin  and @ozgunbabur I have started working with the interface design and I have almost completed the interface building part.  
![appdemo](https://user-images.githubusercontent.com/34870686/121789677-62cd9b80-cbf5-11eb-9369-ae5d367cf075.PNG)
Above is the interface design.
As a next part, I need to add the button functions to upload the file.
I am also facing an issue while debugging the app (Most probably version mismatch error). 
I will upload the code after the successful integration of button events. 
I tried to understand the different components of UI and tried to make it as user-friendly as possible.
Please let me know what are things I need to change. 
Thanks,
@thepritam

**Comment by thepritam** [comment]
@cannin  @ozgunbabur  I have completed the functionalities implementation of the following button. 
1. The two CheckBox
2. The help Button
I got stuck with importing file using file and I have written the code but there is a function which is not getting executed when I press the button.
I also need some help with how to import format files and JSON files in Cytoscape.
As I have completed the interface design and implementation, I am going ahead to work on the functionalities of each button.
Please let me know about the changes required in UI Design.
I have also asked about some help in the Cytoscape App Development community. 
This is my conversation request to this group. https://groups.google.com/g/cytoscape-app-dev/c/I_a9kglUP2E
Thanks,
Pritam Saha

**Comment by cannin** [comment]
Thanks. It is good you were able to design the interface. I have comments on the interface, but before I make them, it is important for me to know how causalpath.jar will run in the Cytoscape app. I have made a new issue #10  Let's figure that one out first.

**Comment by thepritam** [comment]
@cannin the following link described my query which I have asked in the Cytoscape-app-development group.
https://groups.google.com/u/1/g/cytoscape-app-dev/c/PJZlTdwgePo

**Comment by thepritam** [comment]
@cannin  @ozgunbabur I have modified some of the features of the UI to make the app work properly. 
Below are some of screenshot of the user Interface:
![Jsonview](https://user-images.githubusercontent.com/34870686/125211912-8274e400-e2c7-11eb-84d6-467d0206824e.PNG)
![sif1view](https://user-images.githubusercontent.com/34870686/125211921-8ef93c80-e2c7-11eb-8274-78a9d8a2d49d.PNG)
![formatandhelpdialog](https://user-images.githubusercontent.com/34870686/125211924-9587b400-e2c7-11eb-832a-fa7135d17caf.PNG)
